# ML Linear Regression Home Price Prediction & Analysis Project

Column details(Meta description)


Suburb: Suburb

Address: Address

Rooms: Number of rooms

Price: Price in Australian dollars

Method:

S - property sold;

SP - property sold prior;

PI - property passed in;

PN - sold prior not disclosed;

SN - sold not disclosed;

NB - no bid;

VB - vendor bid;

W - withdrawn prior to auction;

SA - sold after auction;

SS - sold after auction price not disclosed.

N/A - price or highest bid not available.

Type:



br - bedroom(s);

h - house, cottage, villa, semi, terrace;

u - unit, duplex;

t - townhouse;

dev site - development site;

o res - other residential.

SellerG: Real Estate Agent

Date: Date sold

Distance: Distance from CBD in Kilometres

Regionname: General Region (West, North West, North, North east …etc)

Propertycount: Number of properties that exist in the suburb.

Bedroom2 : Scraped # of Bedrooms (from different source)

Bathroom: Number of Bathrooms

Car: Number of cars spots

Landsize: Land Size in Metres

BuildingArea: Building Size in Metres

YearBuilt: Year the house was built

CouncilArea: Governing council for the area

Lattitude: Self explanatory

Longtitude: Self explanatory

# Part-1: Data Exploration and Pre-processing

# 1) Load the given dataset

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\nisth\Downloads\ML PROJECTS\ML PROJECT CSV DATASET\1768299091977-ML Linear Regression Home Price Prediction & Analysis Project  Resource16932049360.csv")

In [4]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

# 2) Print all the column names

In [5]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [6]:
df.shape

(34857, 21)

# 3) Describe the data

In [7]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [8]:
df.describe(include='object')

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
count,34857,34857,34857,34857,34857,34857,34854,34854
unique,351,34009,3,9,388,78,33,8
top,Reservoir,5 Charles St,h,S,Jellis,28-10-2017,Boroondara City Council,Southern Metropolitan
freq,844,6,23980,19744,3359,1119,3675,11836

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [10]:
df.duplicated().sum()

1

In [11]:
df.drop_duplicates(inplace = True , ignore_index = True)

# 4) Drop address, date, postcode, YearBuilt, lattitude, longtitude columns

In [12]:
df = df.drop(['Address','Date','Postcode','YearBuilt','Lattitude','Longtitude'], axis=1)

In [13]:
df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0

# 5) Find the count of null value in each column

In [14]:
df.isnull().any()

Suburb           False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Distance          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
CouncilArea       True
Regionname        True
Propertycount     True
dtype: bool

In [15]:
df.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7609
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [16]:
import warnings
warnings.filterwarnings('ignore')

# 6) Fill the null value of property count, distance, Bedroom2, Bathroom, Car with 0

In [17]:
df = df.dropna(subset=['Price'])

In [18]:
df[['Propertycount','Distance','Bedroom2','Bathroom','Car']] = df[['Propertycount','Distance','Bedroom2','Bathroom','Car']].fillna(0)

In [19]:
df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
5,Abbotsford,3,h,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
6,Abbotsford,4,h,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.0,142.0,Yarra City Council,Northern Metropolitan,4019.0

In [20]:
df.isnull().any()

Suburb           False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Distance         False
Bedroom2         False
Bathroom         False
Car              False
Landsize          True
BuildingArea      True
CouncilArea       True
Regionname        True
Propertycount    False
dtype: bool

# 7) Fill Null value of land size and bidding area columns with Mean

In [21]:
df['Landsize'].mean()

593.4889333778223

In [23]:
df["Landsize"].fillna(df["Landsize"].mean() , inplace = True)

In [24]:
df['BuildingArea'].mean()

156.83458555743243

In [25]:
df["BuildingArea"].fillna(df["BuildingArea"].mean() , inplace = True)

In [26]:
df.isnull().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      3
Regionname       3
Propertycount    0
dtype: int64

In [27]:
df['CouncilArea'] = df['CouncilArea'].fillna('Unknown')

df['Regionname'] = df['Regionname'].fillna('Unknown')

In [28]:
df.isnull().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Regionname       0
Propertycount    0
dtype: int64

# 8) Find the unique value in method column

In [29]:
df["Method"].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [30]:
df['Method'].value_counts()

Method
S     17515
SP     3603
PI     3255
VB     2684
SA      190
Name: count, dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27247 entries, 1 to 34855
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27247 non-null  object
 1   Rooms          27247 non-null  int64
 2   Type           27247 non-null  object
 3   Price          27247 non-null  float64
 4   Method         27247 non-null  object
 5   SellerG        27247 non-null  object
 6   Distance       27247 non-null  float64
 7   Bedroom2       27247 non-null  float64
 8   Bathroom       27247 non-null  float64
 9   Car            27247 non-null  float64
 10  Landsize       27247 non-null  float64
 11  BuildingArea   27247 non-null  float64
 12  CouncilArea    27247 non-null  object
 13  Regionname     27247 non-null  object
 14  Propertycount  27247 non-null  float64
dtypes: float64(8), int64(1), object(6)
memory usage: 3.3+ MB

# 9) Create a dummy data for categorical data

In [32]:
df = pd.get_dummies(df,columns=['Suburb','Type','Method','SellerG','CouncilArea','Regionname'],drop_first=True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27247 entries, 1 to 34855
Columns: 748 entries, Rooms to Regionname_Western Victoria
dtypes: bool(739), float64(8), int64(1)
memory usage: 21.3 MB

In [34]:
df

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,...,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Unknown,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,156.834586,4019.0,False,...,True,False,False,True,False,False,False,False,False,False
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.000000,4019.0,False,...,True,False,False,True,False,False,False,False,False,False
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.000000,4019.0,False,...,True,False,False,True,False,False,False,False,False,False
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,156.834586,4019.0,False,...,True,False,False,True,False,False,False,False,False,False
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.000000,4019.0,False,...,True,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,156.834586,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34852,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.000000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34853,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.000000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34854,3,1140000.0,6.3,0.0,0.0,0.0,593.488933,156.834586,6543.0,False,...,False,False,False,False,False,False,False,False,True,False
34855,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.000000,6543.0,False,...,False,False,False,False,False,False,False,False,True,False

In [35]:
df.columns

Index(['Rooms', 'Price', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'Propertycount', 'Suburb_Aberfeldie',
       ...
       'CouncilArea_Yarra City Council',
       'CouncilArea_Yarra Ranges Shire Council', 'Regionname_Eastern Victoria',
       'Regionname_Northern Metropolitan', 'Regionname_Northern Victoria',
       'Regionname_South-Eastern Metropolitan',
       'Regionname_Southern Metropolitan', 'Regionname_Unknown',
       'Regionname_Western Metropolitan', 'Regionname_Western Victoria'],
      dtype='object', length=748)

# Part-2: Working with Model

# 1) Create the target data and feature data where target data is price

In [36]:
#1) Create the target data and feature data where target data is price

In [37]:
x = df.drop('Price' , axis = 1)
y = df['Price']

In [38]:
import matplotlib.pyplot as plt

In [39]:
print(len(x))
print(len(y))

27247
27247

In [40]:
print(x.shape)
print(y.shape)

(27247, 747)
(27247,)

In [41]:
from sklearn.model_selection import train_test_split

In [104]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.8,random_state=)

# 2) Create a linear regression model for Target and feature data

In [105]:
from sklearn.linear_model import LinearRegression

In [106]:
model = LinearRegression()

In [107]:
model.fit(x_train,y_train)

LinearRegression()

# 3) Check if the model is overfitting or underfitting or it is accurate

In [108]:
y_pred = model.predict(x_test)

In [109]:
model.score(x_train, y_train)*100

69.19939053637006

In [111]:
model.score(x_test, y_test)*100

50.91323489729043

# 5) Extract slope and intercept value from the model

In [112]:
print(model.intercept_)

501412.8170506216

In [113]:
print(model.coef_)

[ 2.60581485e+05 -3.04988735e+04 -7.31727773e+04  1.08211877e+05
  3.56898598e+04  1.57052881e+00  3.93839417e+02  9.71501399e+00
  3.80795788e+05 -7.88255583e+04  4.14729584e-10  4.46306935e+05
  1.16612583e+05  4.05217266e+05  1.69573075e+05 -2.88354167e+05
 -1.93125300e+05 -1.38177703e+04  3.60580286e+05 -1.45247001e+05
  3.52273699e+04 -1.82553667e+04  2.29650296e+05 -1.72969670e+05
 -5.30815805e+04 -2.44324709e+05 -2.57247840e+04 -5.77651291e+04
  1.10871167e+05  1.03290425e+04  1.70660711e+04  1.04190604e+05
  2.66546049e+05 -4.65661287e-09 -4.62970874e+03 -9.38433117e+04
  5.73073241e+04 -1.20158596e+05  5.51937792e+04  1.28505160e+05
  2.24422938e+05 -8.82158602e+04  1.07772349e+05 -1.12014236e+05
  1.17527354e+04 -1.72294676e-08  2.46992061e+05 -1.21921275e+05
 -2.14948650e+03  4.22446414e+05 -3.03864294e+04 -7.09966046e+04
 -5.58793545e-08  1.40394454e+05  3.97857175e+04  9.94546314e+04
  1.91039947e+04  9.26665962e-08 -7.40302106e+04  2.00967204e+06
 -1.39309982e+05  1.77320950e+05 -2.19549055e+05 -3.10865647e+05
 -1.04842484e+05 -1.65581009e+05 -1.03000517e+05  9.48767290e+04
 -1.50623444e+05  7.55893612e+05  1.10165123e+04  4.14996110e+05
 -2.74292484e+04 -1.80755014e+05  1.64864072e+05 -1.55234872e+05
 -8.13493913e+04 -3.15830607e+04  4.35937491e+04  5.34906299e+04
 -1.36891675e+05  1.96669758e+05  1.58620779e+05 -2.96152262e+05
 -9.11825573e+04 -2.09849338e+05 -6.17541595e+03 -1.86327421e+05
  2.56961616e+05 -2.45636329e-08 -1.20282681e+05 -1.37615255e+05
  4.28990461e-08  4.37768114e+04 -8.54320862e+04 -1.15184769e+05
  4.27661964e+04  3.55648808e-08 -3.96394171e-08  1.97966219e+05
  4.36248713e+04 -4.25633542e+04 -2.17667384e+05 -1.94482461e+04
  9.94770424e+04 -2.08037785e+05 -1.27331930e+05 -3.22417885e+05
  2.45636329e-08 -6.38848860e+05 -1.43559489e+05 -3.74320323e+04
 -9.72306001e+04  1.99442893e+04  4.77004806e+05 -2.11826474e+05
  0.00000000e+00 -1.71068081e+04 -2.81663465e+04  7.61061050e+03
 -7.56538299e+04 -3.41004669e+05  6.77039841e+05  1.27921485e+05
  1.40199588e+05  2.43675319e+05 -1.18123210e+05 -2.00031705e+03
  8.77451594e+04  3.31783667e-09 -3.75932383e+05 -8.60284235e+04
  7.12623665e+04  3.91392659e+04 -1.16826529e+05  9.15930298e+04
  1.24291546e-08  1.66371692e+05  9.09948566e+04 -7.11588655e-09
  1.11080808e+05  2.67173164e-08  2.50529351e+05  3.03405470e+05
 -7.58014260e+04 -3.60777103e+03 -3.91439427e+04  5.93758589e+04
  4.57699228e+03  3.08657226e+05 -1.87983371e+05  4.06754277e+06
  1.10594556e-08 -1.19277746e+05 -8.71916024e+04 -9.99812335e+04
  1.95166330e+05 -1.29367703e+05 -1.97546677e+05 -1.36989547e+04
 -1.03594665e+04 -1.12156107e+05  3.16358637e-08  1.26749455e+05
 -1.70864545e+05  1.68762231e+04 -8.34522014e+04  6.92417560e+04
 -7.77072273e-09 -9.86184064e+04  9.65099247e+04 -2.12723598e+04
 -2.11587726e+05 -3.06212160e+05 -3.78120215e+04 -1.02836466e+05
 -1.39845129e+04  3.33923353e+04 -1.10871750e+05  2.77880912e+05
  1.27860423e+05  3.63646404e+05  4.47253033e+03 -3.49245965e-09
 -1.34072877e+05  2.59924887e+05  3.95063899e+04  5.06860724e+04
  1.51194399e-08  1.86729347e+05 -4.58533368e+04 -1.73735393e+05
 -5.27527823e+04  1.27835247e+05  9.60365603e+04 -7.36895570e+04
 -1.37657908e+05  7.96947954e+04 -8.18210270e+04 -5.20451635e+05
  4.46433806e+05 -9.62619350e+04  2.84800981e+04  7.48519460e+04
 -3.25607814e+05 -4.35956137e+04  1.27474777e-08  1.30385160e-08
  1.74028451e+05 -7.22345184e+04  3.25205643e+05 -6.28014592e+04
 -3.31092337e+04  2.10615687e+05 -1.32659328e+05 -6.21317501e+04
 -9.96899914e+04  2.79301064e+04  4.56609749e+05  1.00273464e+05
 -6.47531039e+04  1.10451991e+03  2.14489523e+05 -1.90848117e+05
 -3.72649748e+04  1.34314178e-08  1.30205992e+05 -2.12536011e+05
 -6.69388101e-10  7.84273656e+04 -1.68120499e+05 -7.32373878e+04
  2.02859018e+05  1.59569503e+05  9.85661660e+04  2.69704007e+05
  3.87409128e+04  1.86965425e+05 -1.32256619e+07 -1.07478739e+05
  3.35889951e+04  4.82045467e+04  1.33376101e+04  1.92667358e-08
  2.13936622e+05 -1.92667358e-08  2.49357702e+04  6.55274070e+04
  3.43591046e+04  1.23147029e+03 -1.05225952e+05 -2.74720551e+04
  2.21813255e+04 -9.84363139e+04  2.31678765e+05  2.80578566e+05
 -5.79921127e+04 -3.36826738e+03  6.83940016e-09 -1.81828501e+04
 -1.77595739e+05 -6.85537545e+04 -1.84474000e+05 -1.59853677e+05
  5.06625131e+05  2.94967322e-08 -2.54581040e+05 -8.52385002e+04
  4.21051843e+06  3.15744841e+04  1.04242141e+05 -8.89062753e+04
 -3.21856037e+04 -1.14669092e-08 -4.52179088e+04 -1.78567570e+05
 -8.99278457e+04 -1.60552448e+05  2.63499461e+05  1.67588337e+05
 -1.94940175e+05  1.38380148e+05  1.65426597e+05  8.40097335e+04
 -1.83354132e-08 -9.95128794e+04 -9.33795036e+03 -1.71174695e+05
 -1.28100448e+05 -1.65855157e+05 -3.53243044e+05 -1.32486963e+05
  2.19318175e+05 -1.39989424e-08 -1.47533236e+04 -3.02679837e-09
 -1.99751092e+05  1.62150239e+04  2.77650543e-08  2.94220730e+05
  6.80333417e+04 -5.79670032e+04 -1.72804123e+05  7.03246395e+04
  1.34503698e+04  1.04623753e+04 -1.59723526e+05 -4.13080468e+04
  1.06531697e+05  1.11242858e+05 -1.25583915e+05  1.68044752e+05
 -1.88990542e+04  9.64491996e+04  3.58434376e+05  1.80873608e+05
  8.85882795e+04  5.74045309e+04  3.55066732e-09  4.20770832e+04
 -1.31110956e+05 -2.32684379e+05  5.11247620e+05  1.52769515e+05
 -7.67289876e+04 -1.56123232e+05  3.37853754e+05 -2.23754718e+05
  9.54605639e-09  5.56659341e+04 -7.44084035e+04  2.06023949e+05
 -1.01829972e+05  1.02460372e+05 -4.72250128e+04  7.45757204e+04
  2.47537502e+04 -1.56617465e+05  5.20339231e+05  2.21189111e-09
 -2.71613983e+05  4.31943536e+05  1.98122278e+05 -1.07135220e+05
  7.14593775e+04 -2.09292921e-08  2.73883127e+05 -9.90658284e+04
 -1.31021807e-08  1.47088465e+05 -4.30749836e+04  2.04890966e-08
 -2.76551271e+05 -4.56349955e+05  5.86585622e+04  3.69759081e+04
  2.49305385e+04 -2.79228779e+03  2.96859071e-09  1.26892701e-08
  1.06251990e+06  2.91555860e+05 -1.63927325e-08 -1.14523573e-08
  9.19658040e+04  7.45058060e-09 -2.45252064e+05 -7.71251507e-09
 -2.83886952e+05 -6.21421866e+04  3.57449683e+05  3.95812094e-09
 -2.44433211e+05 -1.41080818e-08 -4.51573151e+05 -4.13274392e-09
  7.15954229e-09  1.55559974e-08 -3.81454478e+04 -2.92848034e+04
  1.09139364e-08 -5.83376784e+04 -8.75060583e+04 -2.01960716e+05
 -1.36121948e+05  4.25643520e-09  1.68802217e-09 -3.70138327e+05
  8.70204531e-09 -4.85441185e+04  5.90635436e+04  4.99842823e+03
  7.42861882e+05 -1.49884727e-08  2.67755240e-09 -1.44354999e-08
 -3.06057032e+05 -2.30519141e+04 -3.70503253e+04  2.62356721e+04
 -1.28247919e+05 -1.04620261e+05 -3.77181382e+04  9.25501809e-09
 -1.45014391e+05 -2.08364286e+04  1.46683306e-08  3.14321369e-09
  3.02756321e+05 -5.58793545e-09 -7.99343437e+03  9.32777766e-09
 -1.25778534e+04 -2.00664813e+04 -6.08270057e-09  1.05894885e+05
  6.51079929e+04 -1.95425862e+04  2.40688678e-08 -3.23091167e+05
  4.54019755e-09 -5.59043486e+04 -4.76138666e-08 -1.06750031e+05
 -2.36739870e+05 -1.34459697e-08  5.90381835e+03  6.00847393e+04
 -6.28642738e-09  5.79166226e-09  1.38758263e+05  7.91624188e-09
 -7.91432114e+04 -2.70207640e+05 -1.36060407e-09 -1.29162544e+05
  7.45058060e-09  3.02679837e-09 -7.56699592e-10  7.87986210e-09
  1.30730083e+05 -3.84170562e-09  4.44464388e+04 -1.23309062e+05
  1.57160684e-09 -3.30802651e+04 -5.30630374e+05 -3.25962901e-09
 -2.93678402e+04  1.57370490e+04  2.65106012e+05  8.38190317e-09
 -3.11726428e+03 -3.10086197e+04  5.52972779e-10  4.44266862e+05
 -2.77731311e+04 -5.32600097e-09 -2.70301825e-09  4.14001988e-09
  1.42764592e+06  9.32065129e+03  1.45519152e-09 -1.04191713e-08
 -5.45163571e+04  5.18048182e-09  5.79166226e-09 -1.99513004e+05
 -1.62621434e+05 -4.95232619e+05 -2.31458395e+05  1.20344339e-08
  1.21668563e+04  3.26317916e+04  6.12635631e-09 -4.57247742e+04
  2.13464240e+06 -1.08588807e+05  5.58793545e-09 -5.07517823e+04
 -2.89248725e+05 -7.40180335e+04 -1.92085281e-09 -1.26939026e+05
 -7.80476641e+04 -1.62981451e-09  4.65661287e-10  4.98697013e+05
  9.86680446e+04 -4.01623451e+03  9.85555374e+04 -1.68800190e+05
 -4.08763003e+05 -1.12533258e+05 -2.91927674e+05 -3.52156349e-09
  3.05681169e-09 -1.70172616e+04  5.30453497e+03  4.65110385e+04
 -8.14907253e-10 -6.86850399e-09  4.43913738e+04 -2.69589133e+05
  8.25724580e+04  1.57160684e-09 -8.25984361e+04  3.89991328e-09
  3.86004581e+05 -7.58518581e-10  2.00967204e+06  1.63661334e+05
 -8.20597324e+04  1.74622983e-10 -1.33172013e+05 -1.26523049e+05
 -1.43880905e+05  7.70297291e+05  1.74622983e-10 -2.34244477e+05
  1.06076473e+05 -1.50587786e+05 -7.33416528e-09 -1.71208298e+04
 -2.11957388e+05  5.93649174e+05  5.49490317e+04  2.91038305e-11
  1.58539848e-12 -1.09139364e-11  2.14743042e+05 -1.07784980e+05
  0.00000000e+00 -6.32705065e+04 -6.80515199e+05 -3.13585902e+04
  0.00000000e+00  3.01665184e+05 -1.49741119e+05  5.08071221e+04
  3.09013222e+05 -4.16265017e+03  0.00000000e+00 -2.98015649e+04
 -2.56099856e+05  0.00000000e+00  4.02662484e+04  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -9.77912211e+04
 -1.45194107e+05  7.40381845e+04 -2.43108485e+04  0.00000000e+00
  1.07369798e+05 -7.01950741e+04 -3.81962015e+05  2.49103325e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.23923122e+04
 -1.51460913e+05  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -1.55174834e+05  2.29890783e+05 -1.92494649e+04  0.00000000e+00
  1.93052742e+04 -3.60616527e+05  3.80641745e+05  0.00000000e+00
  2.12901778e+05 -6.84104157e+04  0.00000000e+00  0.00000000e+00
 -1.46639542e+05  0.00000000e+00 -4.37730945e+02  0.00000000e+00
 -5.07488674e+04  0.00000000e+00 -1.67274737e+03 -9.06524259e+04
  0.00000000e+00 -2.59225830e+05  2.66546049e+05  3.58190514e+05
 -1.13460890e+05  5.04822295e+04 -2.27023656e+04 -2.41371937e+05
  0.00000000e+00  0.00000000e+00 -1.45147813e+05 -1.73570448e+05
  2.89445601e+05  0.00000000e+00  0.00000000e+00 -1.43940874e+05
  0.00000000e+00 -3.65118528e+05 -8.17383889e+04  0.00000000e+00
  1.54707613e+05  1.37344173e+04 -4.94086372e+04  0.00000000e+00
 -7.34171882e+04 -1.97388840e+05  0.00000000e+00  0.00000000e+00
  2.19574857e+05  0.00000000e+00  3.65119461e+04 -1.24564190e+05
 -1.13388722e+05  1.63294270e+04  0.00000000e+00 -1.81400751e+05
 -7.61730373e+04  0.00000000e+00  1.82055420e+05 -1.18011065e+05
  0.00000000e+00  1.85132285e+05  5.98593635e+04  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.50663192e+05
 -2.63808666e+04  0.00000000e+00  0.00000000e+00 -6.29339628e+05
  1.68717975e+06  0.00000000e+00  0.00000000e+00 -1.20516388e+05
  0.00000000e+00 -2.89707898e+04  0.00000000e+00 -9.66394546e+04
  0.00000000e+00 -2.89444537e+04  0.00000000e+00  0.00000000e+00
  9.03658157e+04  2.87206790e+04 -1.19711476e+05  0.00000000e+00
 -2.14736454e+05  1.74508436e+04  6.01643970e+04  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.80378635e+05
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -3.02350024e+05 -1.77046188e+04 -1.39968628e+05  0.00000000e+00
  0.00000000e+00 -9.22038787e+04  0.00000000e+00  1.40689334e+05
  1.10305882e+05 -3.08726657e+05  0.00000000e+00 -6.12836133e+03
  7.21575523e+04 -6.97423579e+04 -8.20991345e+04 -4.02240081e+05
  0.00000000e+00 -3.24632214e+04 -3.85434028e+04  0.00000000e+00
 -2.93192431e+04  0.00000000e+00  5.63461603e+04 -6.08491476e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  6.91553609e+04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -5.24343114e+05  0.00000000e+00  0.00000000e+00  8.47992689e+04
 -5.76024191e+04 -1.52092477e+05  4.01355523e+05  3.10214674e+05
 -5.97298281e+04  1.40637680e+05 -1.25576180e+05  7.19842183e+04
  1.24170124e+05  1.33909678e+05 -5.43918465e+04  1.14194137e+05
 -1.43029463e+05  1.56495474e+05 -1.77081126e+04 -2.93792870e+06
  1.47849437e+05  3.26951833e+04  2.75991538e+04  1.50987534e+05
  3.07958581e+04  5.11247620e+05  9.87652568e+04  2.15078616e+05
 -2.57247840e+04  3.02146205e+04  4.28195320e+05  1.80529878e+05
  2.76493211e+05 -8.20148368e+04  1.17870605e+05  6.90752702e+03
 -1.78218333e+05  2.04752396e+05 -7.11570426e+04  1.57731507e+05
 -1.62060339e+05 -5.75102972e+05  1.08910757e+05  1.14646153e+05
 -8.20148368e+04 -2.22066925e+05 -9.74846690e+04]

In [114]:
coef = pd.DataFrame({
    'Feature': x.columns,
    'Coef': model.coef_
})

coef.sort_values(
    by='Coef',
    ascending=False
)

                                      Feature          Coef
268                     Suburb_Riddells Creek  4.210518e+06
151                           Suburb_Gisborne  4.067543e+06
476                              SellerG_Hall  2.134642e+06
59                        Suburb_Bullengarook  2.009672e+06
510                          SellerG_Keatings  2.009672e+06
..                                        ...           ...
109                           Suburb_Deepdene -6.388489e+05
635                             SellerG_Scott -6.506632e+05
534                          SellerG_Maitland -6.805152e+05
719  CouncilArea_Macedon Ranges Shire Council -2.937929e+06
238                       Suburb_New Gisborne -1.322566e+07

[747 rows x 2 columns]

# 6) Display Mean Squared Erro

In [115]:
from sklearn.metrics import mean_squared_error , mean_absolute_error , r2_score , root_mean_squared_error

In [116]:
mean_squared_error(y_test, y_pred)

202437580435.0238

# 7) Display Mean Absolute Error

In [117]:
mean_absolute_error(y_test, y_pred)

245884.7596447178

# 8) Display Root mean Squared error

In [118]:
root_mean_squared_error(y_pred , y_test)

449930.63958239584

# 9) Display R2 score

In [119]:
r2_score(y_pred,y_test)

0.40992402207214096